### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by unclechu** [unclechu/node-deep-extend#16]

**Comment by tsturzl** [comment]
What does this mean? Just having a callback? It doesn't really make any sense, because either way this will block being that its a logical task not something thats being waited on like IO. Having a callback would just make it messier to use and increase the amount of used stack space by creating an unnessesary function.

**Comment by kevin-smets** [comment]
If people really want this, they could always use bluebird and promisify the extend. Not that I really see the benefit in making this operation async. Can it become real slow for heavy objects or something?

**Comment by unclechu** [comment]
Decided not to do it.
